sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t narasimhaconnect/docker-react-web -f Dockerfile.dev .

script:
  - docker run -e CI=true narasimhaconnect/docker-react-web npm run test